name: tiketku
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  google_fonts: ^6.1.0
  page_transition: ^2.1.0
  carousel_slider: ^4.2.1
  camera: ^0.10.5+5
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_native_splash:
  image: assets/tiketku.png
  color: "#FFFFFF"  
  android: true
  ios: true
  web: true
  image_dark: assets/tiketku.png
  android_12:
    icon_background_color: "#FFFFFF"  
    image: assets/tiketku.png
    icon_background_color_dark: "#FFFFFF"
    image_dark: assets/tiketku.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
